# Test Google Books API — POC Data

Objectif :

- tester Google Books API sur une première liste de 20 EAN/ISBN ;
- vérifier la couverture de l’API ;
- analyser rapidement la complétude des métadonnées ;
- capturer les erreurs sans bloquer le notebook ;
- exporter les résultats pour analyse future.

## Import

In [1]:
from pathlib import Path
import sys

import pandas as pd

PROJECT_ROOT = Path.cwd().parents[1]
sys.path.append(str(PROJECT_ROOT / "src"))

from collectionlens.api.google_books_api import search_book_by_isbn

## Liste ISBN test

In [2]:
isbns = [
    "9782351423554",
    "9791042019396",
    "9782820354488",
    "9782290042298",
    "9782845808331",
    "9782413042341",
    "9782384967421",
    "9791043301087",
    "9782374123035",
    "9782374126173",
    "9791039143431",
    "9791026854920",
    "9791039140652",
    "9791026856283",
    "9791039147156",
    "9782203001190",
    "9782858150045",
    "9791038206229",
    "9782822244787",
    "9791038209657",
]

## Fonction de test google books

In [3]:

def build_google_books_results(isbns: list[str]) -> pd.DataFrame:
    """
    Lance un test Google Books sur une liste d'ISBN/EAN.

    La fonction capture les erreurs afin de ne pas interrompre le notebook.

    Args:
        isbns: Liste d'ISBN/EAN à tester.

    Returns:
        DataFrame contenant les résultats normalisés et les erreurs éventuelles.
    """
    rows = []

    for isbn in isbns:
        try:
            result = search_book_by_isbn(isbn)

            if result is None:
                rows.append(
                    {
                        "source": "google_books",
                        "isbn_query": isbn,
                        "found": False,
                        "error": "Aucun résultat ou quota/API indisponible",
                    }
                )
            else:
                rows.append(
                    {
                        "source": "google_books",
                        "isbn_query": isbn,
                        "found": True,
                        "error": None,
                        **result,
                    }
                )

        except Exception as error:
            rows.append(
                {
                    "source": "google_books",
                    "isbn_query": isbn,
                    "found": False,
                    "error": str(error),
                }
            )

    return pd.DataFrame(rows)

## Exécution du test

In [4]:

df_google = build_google_books_results(isbns)

df_google

,source,isbn_query,found,error,source_id,google_books_id,isbn,title,subtitle,authors,...,print_type,maturity_rating,average_rating,ratings_count,preview_link,info_link,canonical_volume_link,industry_identifiers,raw_data,status_code
0,google_books,9782351423554,True,None,f4RwPgAACAAJ,f4RwPgAACAAJ,9782351423554,Vinland Saga,NaN,"[Makoto Yukimura, Xavière Daumarie]",...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=f4RwPgAACAAJ&d...,http://books.google.fr/books?id=f4RwPgAACAAJ&d...,https://books.google.com/books/about/Vinland_S...,"[{'type': 'ISBN_10', 'identifier': '2351423550...","{'kind': 'books#volume', 'id': 'f4RwPgAACAAJ',...",200
1,google_books,9791042019396,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
2,google_books,9782820354488,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
3,google_books,9782290042298,True,None,U4qHPQAACAAJ,U4qHPQAACAAJ,9782290042298,Le précepteur du héros,NaN,[Riku Sanjô],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=U4qHPQAACAAJ&d...,http://books.google.fr/books?id=U4qHPQAACAAJ&d...,https://books.google.com/books/about/Le_pr%C3%...,"[{'type': 'ISBN_10', 'identifier': '2290042293...","{'kind': 'books#volume', 'id': 'U4qHPQAACAAJ',...",200
4,google_books,9782845808331,True,None,xaBwPAAACAAJ,xaBwPAAACAAJ,9782845808331,Dragon quest : la quête de Daï,NaN,"[Riku Sanjô, Kōji Inada, 1964-]",...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=xaBwPAAACAAJ&d...,http://books.google.fr/books?id=xaBwPAAACAAJ&d...,https://books.google.com/books/about/Dragon_qu...,"[{'type': 'ISBN_10', 'identifier': '284580833X...","{'kind': 'books#volume', 'id': 'xaBwPAAACAAJ',...",200
5,google_books,9782413042341,True,None,f9nwzgEACAAJ,f9nwzgEACAAJ,9782413042341,Dragon Quest Tome 1,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=f9nwzgEACAAJ&d...,http://books.google.fr/books?id=f9nwzgEACAAJ&d...,https://books.google.com/books/about/Dragon_Qu...,"[{'type': 'ISBN_10', 'identifier': '2413042342...","{'kind': 'books#volume', 'id': 'f9nwzgEACAAJ',...",200
6,google_books,9782384967421,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
7,google_books,9791043301087,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
8,google_books,9782374123035,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
9,google_books,9782374126173,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
10,google_books,9791039143431,True,None,Bo7r0QEACAAJ,Bo7r0QEACAAJ,9791039143431,La citadelle hurlante,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=Bo7r0QEACAAJ&d...,http://books.google.fr/books?id=Bo7r0QEACAAJ&d...,https://books.google.com/books/about/La_citade...,"[{'type': 'ISBN_13', 'identifier': '9791039143...","{'kind': 'books#volume', 'id': 'Bo7r0QEACAAJ',...",200
11,google_books,9791026854920,True,None,TMbd0QEACAAJ,TMbd0QEACAAJ,9791026854920,Harley Quinn,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=TMbd0QEACAAJ&d...,http://books.google.fr/books?id=TMbd0QEACAAJ&d...,https://books.google.com/books/about/Harley_Qu...,"[{'type': 'ISBN_13', 'identifier': '9791026854...","{'kind': 'books#volume', 'id': 'TMbd0QEACAAJ',...",200
12,google_books,9791039140652,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
13,google_books,9791026856283,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
14,google_books,9791039147156,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
15,google_books,9782203001190,True,None,a64_DwAAQBAJ,a64_DwAAQBAJ,9782203001190,Tintin au Tibet,NaN,[Hergé],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=a64_DwAAQBAJ&p...,https://play.google.com/store/books/details?id...,https://play.google.com/store/books/details?id...,"[{'type': 'ISBN_13', 'identifier': '9782203001...","{'kind': 'books#volume', 'id': 'a64_DwAAQBAJ',...",200
16,google_books,9782858150045,True,None,lxsCPQAACAAJ,lxsCPQAACAAJ,9782858150045,Titine au bistrot,NaN,[Yan Lindingre],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=lxsCPQAACAAJ&d...,http://books.google.fr/books?id=lxsCPQAACAAJ&d...,https://books.google.com/books/about/Titine_au...,"[{'type': 'ISBN_10', 'identifier': '2858150044...","{'kind': 'books#volume', 'id': 'lxsCPQAACAAJ',...",200
17,google_books,9791038206229,True,None,o9GM0AEACAAJ,o9GM0AEACAAJ,9791038206229,Fleurs de pavés,NaN,[Sylvain Frécon],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=o9GM0AEACAAJ&d...,http://books.google.fr/books?id=o9GM0AEACAAJ&d...,https://books.google.com/books/about/Fleurs_de...,"[{'type': 'ISBN_13', 'identifier': '9791038206...","{'kind': 'books#volume', 'id': 'o9GM0AEACAAJ',...",200
18,google_books,9782822244787,True,None,_M7_0AEACAAJ,_M7_0AEACAAJ,9782822244787,Stranger Trucs,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=_M7_0AEACAAJ&d...,http://books.google.fr/books?id=_M7_0AEACAAJ&d...,https://books.google.com/books/about/Stranger_...,"[{'type': 'ISBN_10', 'identifier': '2822244782...","{'kind': 'books#volume', 'id': '_M7_0AEACAAJ',...",200
19,google_books,9791038209657,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200

## Analyse rapide

In [5]:
## Analyse rapide

In [6]:

coverage_rate = df_google["found"].mean() * 100

print(f"Taux de couverture Google Books : {coverage_rate:.2f}%")

Taux de couverture Google Books : 50.00%

In [7]:

df_google["found"].value_counts(dropna=False)

found
True     10
False    10
Name: count, dtype: int64

## Analyse des erreurs

In [8]:
df_google.loc[~df_google["found"], ["isbn_query", "error"]]

       isbn_query      error
1   9791042019396  no_result
2   9782820354488  no_result
6   9782384967421  no_result
7   9791043301087  no_result
8   9782374123035  no_result
9   9782374126173  no_result
12  9791039140652  no_result
13  9791026856283  no_result
14  9791039147156  no_result
19  9791038209657  no_result

## Complétude des métadonnées

In [9]:

metadata_fields = [
    "title",
    "authors",
    "publisher",
    "published_date",
    "language",
    "description",
    "categories",
    "thumbnail",
]

available_fields = [
    field for field in metadata_fields
    if field in df_google.columns
]

metadata_completeness = (
    df_google[available_fields]
    .notna()
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

metadata_completeness.columns = ["field", "completion_rate"]

metadata_completeness

            field  completion_rate
0           title             50.0
1         authors             50.0
2       publisher             10.0
3  published_date             50.0
4        language             50.0
5     description             20.0
6      categories             50.0
7       thumbnail              5.0

In [10]:
df_google_ok = df_google[df_google["found"]].copy()
df_google_ko = df_google[~df_google["found"]].copy()

display(df_google_ok)
display(df_google_ko)

,source,isbn_query,found,error,source_id,google_books_id,isbn,title,subtitle,authors,...,print_type,maturity_rating,average_rating,ratings_count,preview_link,info_link,canonical_volume_link,industry_identifiers,raw_data,status_code
0,google_books,9782351423554,True,None,f4RwPgAACAAJ,f4RwPgAACAAJ,9782351423554,Vinland Saga,NaN,"[Makoto Yukimura, Xavière Daumarie]",...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=f4RwPgAACAAJ&d...,http://books.google.fr/books?id=f4RwPgAACAAJ&d...,https://books.google.com/books/about/Vinland_S...,"[{'type': 'ISBN_10', 'identifier': '2351423550...","{'kind': 'books#volume', 'id': 'f4RwPgAACAAJ',...",200
3,google_books,9782290042298,True,None,U4qHPQAACAAJ,U4qHPQAACAAJ,9782290042298,Le précepteur du héros,NaN,[Riku Sanjô],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=U4qHPQAACAAJ&d...,http://books.google.fr/books?id=U4qHPQAACAAJ&d...,https://books.google.com/books/about/Le_pr%C3%...,"[{'type': 'ISBN_10', 'identifier': '2290042293...","{'kind': 'books#volume', 'id': 'U4qHPQAACAAJ',...",200
4,google_books,9782845808331,True,None,xaBwPAAACAAJ,xaBwPAAACAAJ,9782845808331,Dragon quest : la quête de Daï,NaN,"[Riku Sanjô, Kōji Inada, 1964-]",...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=xaBwPAAACAAJ&d...,http://books.google.fr/books?id=xaBwPAAACAAJ&d...,https://books.google.com/books/about/Dragon_qu...,"[{'type': 'ISBN_10', 'identifier': '284580833X...","{'kind': 'books#volume', 'id': 'xaBwPAAACAAJ',...",200
5,google_books,9782413042341,True,None,f9nwzgEACAAJ,f9nwzgEACAAJ,9782413042341,Dragon Quest Tome 1,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=f9nwzgEACAAJ&d...,http://books.google.fr/books?id=f9nwzgEACAAJ&d...,https://books.google.com/books/about/Dragon_Qu...,"[{'type': 'ISBN_10', 'identifier': '2413042342...","{'kind': 'books#volume', 'id': 'f9nwzgEACAAJ',...",200
10,google_books,9791039143431,True,None,Bo7r0QEACAAJ,Bo7r0QEACAAJ,9791039143431,La citadelle hurlante,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=Bo7r0QEACAAJ&d...,http://books.google.fr/books?id=Bo7r0QEACAAJ&d...,https://books.google.com/books/about/La_citade...,"[{'type': 'ISBN_13', 'identifier': '9791039143...","{'kind': 'books#volume', 'id': 'Bo7r0QEACAAJ',...",200
11,google_books,9791026854920,True,None,TMbd0QEACAAJ,TMbd0QEACAAJ,9791026854920,Harley Quinn,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=TMbd0QEACAAJ&d...,http://books.google.fr/books?id=TMbd0QEACAAJ&d...,https://books.google.com/books/about/Harley_Qu...,"[{'type': 'ISBN_13', 'identifier': '9791026854...","{'kind': 'books#volume', 'id': 'TMbd0QEACAAJ',...",200
15,google_books,9782203001190,True,None,a64_DwAAQBAJ,a64_DwAAQBAJ,9782203001190,Tintin au Tibet,NaN,[Hergé],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=a64_DwAAQBAJ&p...,https://play.google.com/store/books/details?id...,https://play.google.com/store/books/details?id...,"[{'type': 'ISBN_13', 'identifier': '9782203001...","{'kind': 'books#volume', 'id': 'a64_DwAAQBAJ',...",200
16,google_books,9782858150045,True,None,lxsCPQAACAAJ,lxsCPQAACAAJ,9782858150045,Titine au bistrot,NaN,[Yan Lindingre],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=lxsCPQAACAAJ&d...,http://books.google.fr/books?id=lxsCPQAACAAJ&d...,https://books.google.com/books/about/Titine_au...,"[{'type': 'ISBN_10', 'identifier': '2858150044...","{'kind': 'books#volume', 'id': 'lxsCPQAACAAJ',...",200
17,google_books,9791038206229,True,None,o9GM0AEACAAJ,o9GM0AEACAAJ,9791038206229,Fleurs de pavés,NaN,[Sylvain Frécon],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=o9GM0AEACAAJ&d...,http://books.google.fr/books?id=o9GM0AEACAAJ&d...,https://books.google.com/books/about/Fleurs_de...,"[{'type': 'ISBN_13', 'identifier': '9791038206...","{'kind': 'books#volume', 'id': 'o9GM0AEACAAJ',...",200
18,google_books,9782822244787,True,None,_M7_0AEACAAJ,_M7_0AEACAAJ,9782822244787,Stranger Trucs,NaN,[],...,BOOK,NOT_MATURE,NaN,NaN,http://books.google.fr/books?id=_M7_0AEACAAJ&d...,http://books.google.fr/books?id=_M7_0AEACAAJ&d...,https://books.google.com/books/about/Stranger_...,"[{'type': 'ISBN_10', 'identifier': '2822244782...","{'kind': 'books#volume', 'id': '_M7_0AEACAAJ',...",200

,source,isbn_query,found,error,source_id,google_books_id,isbn,title,subtitle,authors,...,print_type,maturity_rating,average_rating,ratings_count,preview_link,info_link,canonical_volume_link,industry_identifiers,raw_data,status_code
1,google_books,9791042019396,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
2,google_books,9782820354488,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
6,google_books,9782384967421,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
7,google_books,9791043301087,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
8,google_books,9782374123035,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
9,google_books,9782374126173,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
12,google_books,9791039140652,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
13,google_books,9791026856283,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
14,google_books,9791039147156,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200
19,google_books,9791038209657,False,no_result,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200

In [11]:

output_dir = PROJECT_ROOT / "data" / "processed" / "google_books"
output_dir.mkdir(parents=True, exist_ok=True)

full_output_path = output_dir / "google_books_results_full.csv"
ok_output_path = output_dir / "google_books_results_ok.csv"
ko_output_path = output_dir / "google_books_results_ko.csv"

df_google.to_csv(full_output_path, index=False)
df_google_ok.to_csv(ok_output_path, index=False)
df_google_ko.to_csv(ko_output_path, index=False)

full_output_path, ok_output_path, ko_output_path

(WindowsPath('c:/Users/yoann/Documents/mes projets/CollectionLens V2/data/processed/google_books/google_books_results_full.csv'),
 WindowsPath('c:/Users/yoann/Documents/mes projets/CollectionLens V2/data/processed/google_books/google_books_results_ok.csv'),
 WindowsPath('c:/Users/yoann/Documents/mes projets/CollectionLens V2/data/processed/google_books/google_books_results_ko.csv'))


## Premiers constats

Les premiers tests réalisés sur Google Books API montrent plusieurs limites importantes dans le cadre du POC CollectionLens.

### Couverture des ouvrages

Le taux de couverture observé sur l’échantillon testé est d’environ 50 %, ce qui signifie qu’une partie importante des ISBN manga, BD et comics n’est pas retrouvée.

Les ouvrages récents ou issus d’éditions françaises semblent particulièrement moins bien couverts.

### Complétude des métadonnées

Les champs suivants sont relativement bien renseignés :
- titre ;
- auteurs ;
- date de publication ;
- catégories.

En revanche, plusieurs métadonnées restent très incomplètes :
- éditeur ;
- description ;
- miniature (thumbnail).

### Limites identifiées

Les limites suivantes ont été observées :
- couverture incomplète des ISBN ;
- qualité variable des métadonnées ;
- absence fréquente des descriptions ;
- quotas journaliers Google Books API ;
- faible couverture de certains mangas, BD et comics français.

### Conclusion POC

Google Books API constitue une source intéressante pour enrichir certaines métadonnées bibliographiques, mais ne semble pas suffisante comme source unique pour CollectionLens.

Ces résultats justifient :
- l’évaluation d’autres APIs bibliographiques ;
- la mise en place d’une stratégie multi-sources ;
- l’ajout futur de mécanismes de cache et de normalisation.